"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class TrainRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FILEPATH_FIELD_NUMBER: builtins.int
    MAXUSERID_FIELD_NUMBER: builtins.int
    TOTALANIME_FIELD_NUMBER: builtins.int
    filePath: builtins.str
    maxUserId: builtins.int
    totalAnime: builtins.int
    def __init__(
        self,
        *,
        filePath: builtins.str = ...,
        maxUserId: builtins.int = ...,
        totalAnime: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["filePath", b"filePath", "maxUserId", b"maxUserId", "totalAnime", b"totalAnime"]) -> None: ...

global___TrainRequest = TrainRequest

@typing_extensions.final
class TrainResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OK_FIELD_NUMBER: builtins.int
    ok: builtins.bool
    def __init__(
        self,
        *,
        ok: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["ok", b"ok"]) -> None: ...

global___TrainResponse = TrainResponse

@typing_extensions.final
class RecommendationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    @typing_extensions.final
    class AnimeRating(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor

        ID_FIELD_NUMBER: builtins.int
        RATING_FIELD_NUMBER: builtins.int
        id: builtins.int
        rating: builtins.int
        def __init__(
            self,
            *,
            id: builtins.int = ...,
            rating: builtins.int = ...,
        ) -> None: ...
        def ClearField(self, field_name: typing_extensions.Literal["id", b"id", "rating", b"rating"]) -> None: ...

    ANIMES_FIELD_NUMBER: builtins.int
    K_FIELD_NUMBER: builtins.int
    @property
    def animes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___RecommendationRequest.AnimeRating]: ...
    k: builtins.int
    def __init__(
        self,
        *,
        animes: collections.abc.Iterable[global___RecommendationRequest.AnimeRating] | None = ...,
        k: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["animes", b"animes", "k", b"k"]) -> None: ...

global___RecommendationRequest = RecommendationRequest

@typing_extensions.final
class RecommendationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANIMEID_FIELD_NUMBER: builtins.int
    RECOMMENDATIONS_FIELD_NUMBER: builtins.int
    animeId: builtins.int
    @property
    def recommendations(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        animeId: builtins.int = ...,
        recommendations: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["animeId", b"animeId", "recommendations", b"recommendations"]) -> None: ...

global___RecommendationResponse = RecommendationResponse
