"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Recommendation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECOMMENDEDANIMEID_FIELD_NUMBER: builtins.int
    RANK_FIELD_NUMBER: builtins.int
    recommendedAnimeId: builtins.int
    rank: builtins.int
    def __init__(
        self,
        *,
        recommendedAnimeId: builtins.int = ...,
        rank: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["rank", b"rank", "recommendedAnimeId", b"recommendedAnimeId"]
    ) -> None: ...

global___Recommendation = Recommendation

@typing_extensions.final
class Empty(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___Empty = Empty

@typing_extensions.final
class IsTrainedResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAINED_FIELD_NUMBER: builtins.int
    trained: builtins.bool
    def __init__(
        self,
        *,
        trained: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["trained", b"trained"]) -> None: ...

global___IsTrainedResponse = IsTrainedResponse

@typing_extensions.final
class RecommendationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANIMEID_FIELD_NUMBER: builtins.int
    K_FIELD_NUMBER: builtins.int
    EXCLUDEDANIMEIDS_FIELD_NUMBER: builtins.int
    animeId: builtins.int
    k: builtins.int
    @property
    def excludedAnimeIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        animeId: builtins.int = ...,
        k: builtins.int | None = ...,
        excludedAnimeIds: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_k", b"_k", "k", b"k"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "_k", b"_k", "animeId", b"animeId", "excludedAnimeIds", b"excludedAnimeIds", "k", b"k"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["_k", b"_k"]
    ) -> typing_extensions.Literal["k"] | None: ...

global___RecommendationRequest = RecommendationRequest

@typing_extensions.final
class RecommendationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANIMEID_FIELD_NUMBER: builtins.int
    RECOMMENDATIONS_FIELD_NUMBER: builtins.int
    animeId: builtins.int
    @property
    def recommendations(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Recommendation]: ...
    def __init__(
        self,
        *,
        animeId: builtins.int = ...,
        recommendations: collections.abc.Iterable[global___Recommendation] | None = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["animeId", b"animeId", "recommendations", b"recommendations"]
    ) -> None: ...

global___RecommendationResponse = RecommendationResponse

@typing_extensions.final
class GroupRecommendationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ANIMEIDS_FIELD_NUMBER: builtins.int
    K_FIELD_NUMBER: builtins.int
    EXCLUDEDANIMEIDS_FIELD_NUMBER: builtins.int
    @property
    def animeIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    k: builtins.int
    @property
    def excludedAnimeIds(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        animeIds: collections.abc.Iterable[builtins.int] | None = ...,
        k: builtins.int | None = ...,
        excludedAnimeIds: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["_k", b"_k", "k", b"k"]) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "_k", b"_k", "animeIds", b"animeIds", "excludedAnimeIds", b"excludedAnimeIds", "k", b"k"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["_k", b"_k"]
    ) -> typing_extensions.Literal["k"] | None: ...

global___GroupRecommendationRequest = GroupRecommendationRequest

@typing_extensions.final
class GroupRecommendationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    RECOMMENDATIONS_FIELD_NUMBER: builtins.int
    @property
    def recommendations(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Recommendation]: ...
    def __init__(
        self,
        *,
        recommendations: collections.abc.Iterable[global___Recommendation] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["recommendations", b"recommendations"]) -> None: ...

global___GroupRecommendationResponse = GroupRecommendationResponse
