# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import recommender_pb2 as recommender__pb2


class RecommenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
            "/recommender.Recommender/Train",
            request_serializer=recommender__pb2.TrainRequest.SerializeToString,
            response_deserializer=recommender__pb2.TrainResponse.FromString,
        )
        self.GetRecommendations = channel.unary_stream(
            "/recommender.Recommender/GetRecommendations",
            request_serializer=recommender__pb2.RecommendationRequest.SerializeToString,
            response_deserializer=recommender__pb2.RecommendationResponse.FromString,
        )


class RecommenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Train(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def GetRecommendations(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RecommenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Train": grpc.unary_unary_rpc_method_handler(
            servicer.Train,
            request_deserializer=recommender__pb2.TrainRequest.FromString,
            response_serializer=recommender__pb2.TrainResponse.SerializeToString,
        ),
        "GetRecommendations": grpc.unary_stream_rpc_method_handler(
            servicer.GetRecommendations,
            request_deserializer=recommender__pb2.RecommendationRequest.FromString,
            response_serializer=recommender__pb2.RecommendationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("recommender.Recommender", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class Recommender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Train(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/recommender.Recommender/Train",
            recommender__pb2.TrainRequest.SerializeToString,
            recommender__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def GetRecommendations(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/recommender.Recommender/GetRecommendations",
            recommender__pb2.RecommendationRequest.SerializeToString,
            recommender__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
