# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import anime_pb2 as anime__pb2


class AnimeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FetchAnime = channel.stream_unary(
            "/anime.AnimeService/FetchAnime",
            request_serializer=anime__pb2.Anime.SerializeToString,
            response_deserializer=anime__pb2.Void.FromString,
        )
        self.FetchAnimeRating = channel.stream_unary(
            "/anime.AnimeService/FetchAnimeRating",
            request_serializer=anime__pb2.AnimeRating.SerializeToString,
            response_deserializer=anime__pb2.Void.FromString,
        )


class AnimeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FetchAnime(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def FetchAnimeRating(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_AnimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "FetchAnime": grpc.stream_unary_rpc_method_handler(
            servicer.FetchAnime,
            request_deserializer=anime__pb2.Anime.FromString,
            response_serializer=anime__pb2.Void.SerializeToString,
        ),
        "FetchAnimeRating": grpc.stream_unary_rpc_method_handler(
            servicer.FetchAnimeRating,
            request_deserializer=anime__pb2.AnimeRating.FromString,
            response_serializer=anime__pb2.Void.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler("anime.AnimeService", rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class AnimeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FetchAnime(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/anime.AnimeService/FetchAnime",
            anime__pb2.Anime.SerializeToString,
            anime__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def FetchAnimeRating(
        request_iterator,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            "/anime.AnimeService/FetchAnimeRating",
            anime__pb2.AnimeRating.SerializeToString,
            anime__pb2.Void.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
